// UI string dictionaries. Each top-level key is a locale; the header language
// switcher is generated from these keys, so adding a language here is enough
// to surface it in the UI. Values may be functions for locale plural forms.
const I18N = {
  ru: {
    srcLabel: "Ссылка на CSV-файл",
    srcPlaceholder: "https://example.com/results.csv или Google Sheets export",
    loadBtn: "Загрузить",
    localFile: "Локальный файл",
    chooseCsv: "Выбрать CSV",
    searchLabel: "Поиск",
    searchPlaceholder: "Номер или имя",
    statStarters: "Участники",
    statLaps: "Круги",
    tabCumulative: "Суммарное время",
    tabLaps: "Круги",
    tabPosition: "Позиция",
    ariaDataLoad: "Загрузка данных гонки",
    ariaTools: "Инструменты участников",
    ariaRaceSummary: "Сводка гонки",
    ariaSelectedParticipant: "Выбранный участник",
    ariaCharts: "Графики",
    ariaRaceCharts: "Графики гонки",
    ariaComparison: "Табличные данные активного графика",
    ariaResultsTable: "Таблица результатов",
    ariaLang: "Язык интерфейса",
    loadingUrl: "Загружаем данные...",
    loadingFile: "Читаем файл...",
    errLoadUrl: "Не удалось загрузить CSV по URL: {message}",
    errReadFile: "Не удалось прочитать CSV-файл: {message}",
    errCsvMinRows: "CSV должен содержать строку заголовков и хотя бы одного участника.",
    errNoLapColumns: "В CSV должны быть колонки кругов: lap1, lap2, lap3 и так далее.",
    errLapOrder: "Колонки кругов должны идти по порядку без пропусков и дубликатов: lap1, lap2, lap3 и так далее.",
    errMissingColumns: "В CSV нет обязательных колонок: {columns}.",
    errIssuesCount: "Проблемных строк: {count}.",
    errEmptyField: "В строке {row} пустое обязательное поле {field}.",
    errLapDecreasing: "Кумулятивное время в строке {row}, {header} меньше предыдущей отметки.",
    errPlace: "В строке {row} место должно быть положительным целым числом или статусом (DNF, DNS, DSQ): {value}.",
    errTimeFormat: "Некорректная отметка времени в строке {row}, {header}: {value}. Используйте формат [HH:]MM:SS.",
    errTimeValue: "Некорректная отметка времени в строке {row}, {header}: {value}.",
    noticeTitle: "Файл не загружен. Проблемных строк: {count}. Исправьте их и загрузите снова.",
    noticeMore: (params) => `...и еще ${params.count} ${pluralRu(params.count, "строка", "строки", "строк")}.`,
    genderF: "Ж",
    genderM: "М",
    genderUnknown: "Не указан",
    cardEmptyNoData: "Загрузите CSV по ссылке или с диска, чтобы увидеть результаты.",
    cardEmptySelect: "Выберите участника",
    favorite: "Избранное",
    favAdd: "Показать на графиках",
    favRemove: "Убрать с графиков",
    finishLabel: "Финиш",
    lastSplitLabel: "Последняя отметка",
    metaBib: "Номер",
    metaEvent: "Соревнование",
    metaGroup: "Зачет",
    metaCourse: "Трасса",
    metaGender: "Пол",
    statPlace: "Место",
    statGap: "Отставание",
    statBestLap: "Лучший круг",
    statLapSpread: "Разброс кругов",
    thName: "Имя",
    chartColumn: "График",
    chartsEmptyNoData: "Загрузите CSV, чтобы построить графики",
    chartsEmptyCourse: "Выберите одну трассу, чтобы построить графики",
    chartsEmptyNoParticipants: "Нет участников для графика",
    chartsEmptyGroup: "Выберите зачет, чтобы увидеть позиции",
    plotlyFailed: "Не удалось загрузить библиотеку графиков. Проверьте доступ к cdn.plot.ly и обновите страницу.",
    axisLap: "Круг",
    axisCumulative: "Суммарное время",
    axisLapTime: "Время круга",
    axisPosition: "Позиция в зачете",
    scopeNoData: "Графики появятся после загрузки CSV.",
    scopeCourse: "Графики скрыты: выберите одну трассу.",
    scopeComparison: "Сравнение",
    scopeFavorites: "На графиках только отмеченные участники ({count}). Звездочка в таблице добавляет или убирает линию.",
    scopeFavoritesFiltered: "На графиках нет линий: отмеченные участники не попали в текущий фильтр.",
    scopeOverview: "Обзор",
    scopeTop: "На графиках топ-{count} по месту в текущей выборке. Отметьте участников звездой, чтобы перейти к сравнению.",
    cmpSelectedTitle: "Сравнение выбранных",
    cmpSelectCourse: "Выберите одну трассу, чтобы сравнить отмеченных участников по времени.",
    cmpParticipant: "Участник",
    cmpMixedNote: "Сравнение по трассе, без учета зачета.",
    cmpLapsTitle: "Таблица: круги",
    cmpLapsNote: "Разница к лучшему кругу среди выбранных на каждом круге.",
    cmpPositionTitle: "Таблица: позиция",
    cmpPositionNote: "Те же позиции по отметкам, что на графике.",
    cmpCumulativeTitle: "Таблица: суммарное время",
    cmpCumulativeNote: "Нарастание разницы к лучшему из выбранных на каждой отметке.",
    tabPositionHint: "Покажет, как менялась позиция в зачёте по кругам. Доступно для одного зачёта — выберите его в фильтре «Зачёт».",
    optNoData: "Нет данных",
    optAllEvents: "Все соревнования",
    optAllCourses: "Все трассы",
    optAllGroups: "Все зачеты",
    trendEvenOfficial: "Финишировал в темпе первого круга.",
    trendEvenPartial: "Отмеченные круги прошел в ровном темпе.",
    trendFasterOfficial: "Ускорился к финишу: последний круг быстрее первого на {delta}.",
    trendFasterPartial: "Последний отмеченный круг быстрее первого на {delta}.",
    trendSlowerOfficial: "Темп к концу снизился: последний круг медленнее первого на {delta}.",
    trendSlowerPartial: "Темп на последнем отмеченном круге снизился: он медленнее первого на {delta}.",
    trendVeryEven: "Круги прошел очень ровно.",
    trendEven: "Темп был достаточно ровный.",
    trendUneven: "Темп был нестабильным.",
    trendSlowestLap: "Самый долгий круг - {lap}.",
    trendNoData: "Пока мало данных, чтобы оценить темп по кругам."
  },
  en: {
    srcLabel: "CSV file link",
    srcPlaceholder: "https://example.com/results.csv or Google Sheets export",
    loadBtn: "Load",
    localFile: "Local file",
    chooseCsv: "Choose CSV",
    searchLabel: "Search",
    searchPlaceholder: "Bib or name",
    statStarters: "Participants",
    statLaps: "Laps",
    tabCumulative: "Total time",
    tabLaps: "Laps",
    tabPosition: "Position",
    ariaDataLoad: "Race data loading",
    ariaTools: "Participant tools",
    ariaRaceSummary: "Race summary",
    ariaSelectedParticipant: "Selected participant",
    ariaCharts: "Charts",
    ariaRaceCharts: "Race charts",
    ariaComparison: "Active chart table data",
    ariaResultsTable: "Results table",
    ariaLang: "Interface language",
    loadingUrl: "Loading data...",
    loadingFile: "Reading file...",
    errLoadUrl: "Failed to load CSV from URL: {message}",
    errReadFile: "Failed to read the CSV file: {message}",
    errCsvMinRows: "The CSV must contain a header row and at least one participant.",
    errNoLapColumns: "The CSV must contain lap columns: lap1, lap2, lap3 and so on.",
    errLapOrder: "Lap columns must be sequential without gaps or duplicates: lap1, lap2, lap3 and so on.",
    errMissingColumns: "The CSV is missing required columns: {columns}.",
    errIssuesCount: "Rows with issues: {count}.",
    errEmptyField: "Row {row} has an empty required field {field}.",
    errLapDecreasing: "Cumulative time in row {row}, {header} is less than the previous split.",
    errPlace: "Row {row}: place must be a positive integer or a status (DNF, DNS, DSQ): {value}.",
    errTimeFormat: "Invalid time split in row {row}, {header}: {value}. Use the [HH:]MM:SS format.",
    errTimeValue: "Invalid time split in row {row}, {header}: {value}.",
    noticeTitle: "The file was not loaded. Rows with issues: {count}. Fix them and load the file again.",
    noticeMore: (params) => `...and ${params.count} more ${params.count === 1 ? "row" : "rows"}.`,
    genderF: "F",
    genderM: "M",
    genderUnknown: "Not specified",
    cardEmptyNoData: "Load a CSV from a link or your computer to see the results.",
    cardEmptySelect: "Select a participant",
    favorite: "Favorite",
    favAdd: "Show on charts",
    favRemove: "Remove from charts",
    finishLabel: "Finish",
    lastSplitLabel: "Last split",
    metaBib: "Bib",
    metaEvent: "Event",
    metaGroup: "Group",
    metaCourse: "Course",
    metaGender: "Gender",
    statPlace: "Place",
    statGap: "Gap",
    statBestLap: "Best lap",
    statLapSpread: "Lap spread",
    thName: "Name",
    chartColumn: "Chart",
    chartsEmptyNoData: "Load a CSV to build charts",
    chartsEmptyCourse: "Select a single course to build charts",
    chartsEmptyNoParticipants: "No participants to chart",
    chartsEmptyGroup: "Select a group to see positions",
    plotlyFailed: "Failed to load the charting library. Check access to cdn.plot.ly and reload the page.",
    axisLap: "Lap",
    axisCumulative: "Total time",
    axisLapTime: "Lap time",
    axisPosition: "Position in group",
    scopeNoData: "Charts will appear after a CSV is loaded.",
    scopeCourse: "Charts are hidden: select a single course.",
    scopeComparison: "Comparison",
    scopeFavorites: "Charts show only starred participants ({count}). The star in the table adds or removes a line.",
    scopeFavoritesFiltered: "No lines on the charts: starred participants don't match the current filter.",
    scopeOverview: "Overview",
    scopeTop: "Charts show the top {count} by place in the current selection. Star participants to switch to comparison.",
    cmpSelectedTitle: "Starred comparison",
    cmpSelectCourse: "Select a single course to compare starred participants by time.",
    cmpParticipant: "Participant",
    cmpMixedNote: "Course-level comparison, groups are not taken into account.",
    cmpLapsTitle: "Table: laps",
    cmpLapsNote: "Difference to the best lap among the starred on each lap.",
    cmpPositionTitle: "Table: position",
    cmpPositionNote: "The same per-split positions as on the chart.",
    cmpCumulativeTitle: "Table: total time",
    cmpCumulativeNote: "Growing difference to the best of the starred at each split.",
    tabPositionHint: "Shows how the position in the group changed lap by lap. Available for a single group — select it in the Group filter.",
    optNoData: "No data",
    optAllEvents: "All events",
    optAllCourses: "All courses",
    optAllGroups: "All groups",
    trendEvenOfficial: "Finished at first-lap pace.",
    trendEvenPartial: "Completed the recorded laps at a steady pace.",
    trendFasterOfficial: "Sped up toward the finish: the last lap was {delta} faster than the first.",
    trendFasterPartial: "The last recorded lap was {delta} faster than the first.",
    trendSlowerOfficial: "Pace dropped toward the end: the last lap was {delta} slower than the first.",
    trendSlowerPartial: "Pace dropped on the last recorded lap: it was {delta} slower than the first.",
    trendVeryEven: "Lap times were very consistent.",
    trendEven: "Pace was fairly even.",
    trendUneven: "Pace was inconsistent.",
    trendSlowestLap: "Slowest lap: {lap}.",
    trendNoData: "Not enough data yet to assess lap pace."
  }
};

function pluralRu(n, one, few, many) {
  const mod10 = n % 10;
  const mod100 = n % 100;
  if (mod10 === 1 && mod100 !== 11) return one;
  if (mod10 >= 2 && mod10 <= 4 && (mod100 < 10 || mod100 >= 20)) return few;
  return many;
}
